# Generated by Django 6.0.6 on 2026-07-01 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolebasesystem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.company'),
        ),
        migrations.AlterField(
            model_name='rolebasesystem',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
